dist: trusty
sudo: required

language: java

jdk:
  - openjdk8
  - oraclejdk8

script: ./gradlew build checkstyle -Dorg.gradle.daemon=false

branches:
  except:
    - gh-pages

notifications:
  email: false